stages:
  - build
  - migrate
  - test

variables:
  DOTNET_NOLOGO: "true"
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet restore StudyZen.sln
    - dotnet build --no-restore -c Release StudyZen.sln

migrate:
  stage: migrate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  services:
    - name: mcr.microsoft.com/mssql/server:2019-latest
      alias: db
  variables:
    SA_PASSWORD: "YourStrong!Passw0rd"
    ACCEPT_EULA: "Y"
  script:
    - dotnet ef database update --project src/Infrastructure

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test --no-restore --verbosity normal StudyZen.sln
  artifacts:
    when: always
    reports:
      junit: TestResults/*.xml
    paths:
      - TestResults
  only:
    - branches
